### ISSUE TITLE
Можно ли работать в этой компании?

### ISSUE THREAD

**Issue by NightFlexer** [Clusiv/medods#1]
Я новичёк в git, не нашел другого способа связи и решил спросить здесь.
Стоит ли работать в этой компании?

**Comment by Clusiv** [comment]
@NightFlexer 
Фидбека от них не было, просто отказали.
Мое имхо с такими работать не стоит, ты найдешь более достойные варианты.

**Comment by NightFlexer** [comment]
@Clusiv Благодарю за совет
